### ISSUE TITLE
MJML code is not formatted using extension

### ISSUE THREAD

**Issue by Taras-R** [mjmlio/vscode-mjml#58] opened 2024-11-09 16:54 UTC
## Expected behavior

When mjml extension is configured as default formatter in vs code it should format code.

`{
  "editor.formatOnSave": true,
  "[mjml]": {
    "editor.defaultFormatter": "mjmlio.vscode-mjml"
  }
}
`

## Actual behavior

Code is not formatted in any way. Manual formatting displays error that it cannot format mjml files.

![image](https://github.com/user-attachments/assets/17d93f7a-79d2-4639-b4db-01d691631f13)

Am i missing something? I'm pretty sure that some time ago i worked with it and it formatted code as expected, thank you.

**Comment by iRyusa** [comment] 2024-11-09 16:58
Duplicate of #56

**Closed by iRyusa** 2024-11-09 16:58 UTC

**Comment by Taras-R** [comment] 2024-11-09 17:08
@iRyusa thank you for response and sorry for creating this issue, i just looked opened ones and missed it somehow.
